### ISSUE TITLE
Upgrade to `idn-area-data` v3

### ISSUE THREAD

**Issue by fityannugroho** [fityannugroho/idn-area-extractor#31]
## Problem

PR #27 is failed because there is code that needs to be changed following the [upgrade guide](https://github.com/fityannugroho/idn-area-data/blob/main/docs/upgrading/upgrade-to-v3.md).

## TODO

- [ ] Install the `idn-area-data` v3
- [ ] Update the use of type derived from `idn-area-data` in each transformer (`RegencyTransformer`, etc)
- [ ] Update the part of code to get the latest data in `src/index.ts`
